Ongoing PR for next version: NewsML-G2 v2.32
iptc/newsml-g2 pull request #16
Opened 2023-01-13 15:03 UTC by bquinn

2023-03-12 22:15 UTC, sinh8erjones approved these changes

2023-06-02 13:44 UTC, bquinn commented
Approved at IPTC Standards Committee on 17 May 2023.

2023-06-02 13:46 UTC, pauliharman approved these changes

2023-06-02 15:08 UTC, davecompton requested changes
Just one comment re <xs:attributeGroup name="authorityAttributes">

2023-06-02 15:08 UTC, davecompton commented on tests/schema_versions/NewsML-G2_2.32-spec-All-Power.xsd
@bquinn :
<xs:attributeGroup name="authorityAttributes"> is in i/ the pre mtg schema at https://iptc.org/std-dev/NewsML-G2/2.32/specification/NewsML-G2_2.32-spec-All-Power.xsd and ii/ NewsML-G2_2.32-spec-All-Power_1.xsd in this PR  ... but I don't see it in this file?

2023-06-06 12:45 UTC, bquinn commented on tests/schema_versions/NewsML-G2_2.32-spec-All-Power.xsd
I had forgotten to push the copy of the schema that sites in the unit tests folder. But the main schema was correct. Thanks for pointing that out.

2023-06-06 12:51 UTC, merged